#!/bin/sh
# https://github.com/mikesparr/tutorial-react-docker/blob/master/run

set -o nounset \
    -o errexit \
    -o verbose \
    -o xtrace

# Set environment values if they exist as arguments
if [ $# -ne 0 ]; then
  echo "===> Overriding env params with args ..."
  for var in "$@"
  do
    export "$var"
  done
fi

echo "===> ENV Variables ..."
env | sort

npm run build --production

echo "===> Running ... "
exec serve -p 80 -s build
