services:
  redis:
    container_name: elearning_app_redis
    image: "redis:latest"
    networks:
      - bridge

  backend:
    container_name: elearning_app_backend
    image: ghcr.io/bwfiq/elearning_app/elearning-backend
    restart: always
    environment:
      REDIS_HOST: elearning_app_redis
      REDIS_PORT: 6379
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: "False"
    depends_on:
      - redis
    networks:
      - bridge

  celery:
    container_name: elearning_app_celery
    image: ghcr.io/bwfiq/elearning_app/elearning-backend
    restart: always
    command: celery -A backend worker -l info
    environment:
      REDIS_HOST: elearning_app_redis
      REDIS_PORT: 6379
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}  # Replace with a secure key
    depends_on:
      - redis
      - backend
    networks:
      - bridge

  frontend:
    container_name: elearning_app_frontend
    image: ghcr.io/bwfiq/elearning_app/elearning-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
