server {
    listen 80;
    server_name  localhost;

    root /app/static/frontend;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /api/ {
        proxy_pass http://localhost:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
