# Generated by Django 5.1.6 on 2025-03-04 09:02

from django.db import migrations


def create_data(apps, schema_editor):
    User = apps.get_model("users", "User")
    User(username="silverjoe", fullName="Joe Silver", email="joe@email.com").save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
