name: Docker Build and Push to GHCR

on:
  push:
    branches:
      - '**'  # This matches any branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: latest
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }} # This is your GitHub username/repo_name

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }} # Explicitly specify the ref to checkout

      - name: Login to GHCR
        run: |
          docker login $REGISTRY -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Docker Image
        working-directory: ./backend
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME/elearning-backend:$IMAGE_TAG .
          docker push $REGISTRY/$IMAGE_NAME/elearning-backend:$IMAGE_TAG

      - name: Build and Push Frontend Docker Image
        working-directory: ./frontend
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME/elearning-frontend:$IMAGE_TAG ./
          docker push $REGISTRY/$IMAGE_NAME/elearning-frontend:$IMAGE_TAG
